// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Load
---
*/
package cmds

import (
	"context"

	"github.com/magicbutton/magic-devices/execution"
	"github.com/magicbutton/magic-devices/utils"
)

func LoadLoadPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magic-devices", "24-load", "10-load.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
