// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: App deploy to production
---
*/
package cmds

import (
	"context"

	"github.com/magicbutton/magic-devices/execution"
	"github.com/magicbutton/magic-devices/utils"
)

func ProvisionAppdeployproductionPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magic-devices", "60-provision", "20-app-job.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
