// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------

package endpoints

import (
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/swaggest/rest/nethttp"
	"github.com/swaggest/rest/web"
)

func AddEndpoints(s *web.Service, jwtAuth func(http.Handler) http.Handler) {
	s.Route("/v1", func(r chi.Router) {
		r.Group(func(r chi.Router) {
			//r.Use(adminAuth, nethttp.HTTPBasicSecurityMiddleware(s.OpenAPICollector, "User", "User access"))
			r.Use(jwtAuth, nethttp.HTTPBearerSecurityMiddleware(s.OpenAPICollector, "Bearer", "", ""))
			//	r.Use(rateLimitByAppId(50))
			//r.Method(http.MethodPost, "/", nethttp.NewHandler(ExchangeCreateRoomsPost()))
			r.Method(http.MethodPost, "/magic/kpi", nethttp.NewHandler(MagicKpiPost()))
			r.Method(http.MethodPost, "/download/excel", nethttp.NewHandler(DownloadExcelPost()))
			r.Method(http.MethodPost, "/extract/fullkpi", nethttp.NewHandler(ExtractFullkpiPost()))
			r.Method(http.MethodPost, "/extract/intune", nethttp.NewHandler(ExtractIntunePost()))
			r.Method(http.MethodPost, "/extract/tabelle", nethttp.NewHandler(ExtractTabellePost()))
			r.Method(http.MethodPost, "/extract/download-excel", nethttp.NewHandler(ExtractDownloadExcelPost()))
			r.Method(http.MethodPost, "/insert/sql", nethttp.NewHandler(InsertSqlPost()))
			r.Method(http.MethodPost, "/transform/download-excel", nethttp.NewHandler(TransformDownloadExcelPost()))
			r.Method(http.MethodPost, "/load/load", nethttp.NewHandler(LoadLoadPost()))
			r.Method(http.MethodPost, "/provision/appdeployproduction", nethttp.NewHandler(ProvisionAppdeployproductionPost()))
			r.Method(http.MethodPost, "/health/ping", nethttp.NewHandler(HealthPingPost()))
			r.Method(http.MethodPost, "/health/coreversion", nethttp.NewHandler(HealthCoreversionPost()))

		})
	})

}
