// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Import Sheet Tabelle
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/magicbutton/magic-devices/execution"
)

func ImportTabellePost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magic-devices", "20-import", "tabelle.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Import Sheet Tabelle")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Import")
	return u
}
