// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Process KPI
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/magicbutton/magic-devices/execution"
)

func MagicKpiPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magic-devices", "00-magic", "10-process-kpi.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Process KPI")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Magic")
	return u
}
