// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Get KPI report data
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/magicbutton/magic-devices/execution"
)

func RunDevicekpiPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magic-devices", "20-process", "20-getmailwithkpiandprocess.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Get KPI report data")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Processs")
	return u
}
